### ISSUE TITLE
It cant attend on encoder kv, right? 

### ISSUE THREAD

**Issue by hadaev8** [lucidrains/feedback-transformer-pytorch#2]

**Comment by lucidrains** [comment]
@hadaev8 oh hey! i recognize you from the x-transformers repo :) what do you mean by encoder kv?

**Comment by hadaev8** [comment]
@hadaev8 It would be cool to try encoder decoder model.

**Comment by lucidrains** [comment]
ohhh, not at the moment, this is strictly decoder, but i could add an experimental model where it also does cross attention on encoder keys

what is your use-case?

**Comment by hadaev8** [comment]
@lucidrains i want to try tts model.

**Comment by lucidrains** [comment]
@hadaev8 I added what you want on another branch https://github.com/lucidrains/feedback-transformer-pytorch/tree/with-cross-attention#cross-attention let me know how it goes!

**Comment by hadaev8** [comment]
@lucidrains should you also add context mask and attention maps to visualize cross attention?

**Comment by lucidrains** [comment]
@hadaev8 ok, i added context masks https://github.com/lucidrains/feedback-transformer-pytorch/tree/with-cross-attention#cross-attention i'll get to the attention map another day :)

**Comment by hadaev8** [comment]
@lucidrains 
This order doesnt seems to be right
```

                attn,
                ff,
                cross_attn
```

**Comment by hadaev8** [comment]
Also not sure about shared cross_attn_kv_proj

**Comment by hadaev8** [comment]
Looks like it will run self attention in cross attention pass.

**Comment by hadaev8** [comment]
@lucidrains 
Its kind of hard to return attention maps with Residual and PreNorm classes.
Any tips?

**Comment by hadaev8** [comment]
Made it work if someone needs to plot attention.
https://colab.research.google.com/drive/1yPOurhI8Ll3Th92MW88HB8LkYIkROqGJ?usp=sharing

@lucidrains 
Should be this transformer so memory hungry?
Seems like It uses x5 memory.

**Comment by hadaev8** [comment]
Elaborating for a bit.
X transformers 
https://colab.research.google.com/drive/1n653j4Pz9_U7OukhTlUbomAHMvpPXwx0?usp=sharing
Almost 2gb.
https://colab.research.google.com/drive/1dRImydFn3WthOXdLYIvdf5bsqjXcmhC5?usp=sharing
Feedback transformer
9,7gb

Why should it be?
I think memory usage should be around same.
And I can't find anything suspicious in the code.
