### ISSUE TITLE
Should it really be using lower layers output for keys and values? 

### ISSUE THREAD

**Issue by tarvaina** [lucidrains/feedback-transformer-pytorch#3]
Could you explain the logic of how the key-value pairs are formed at these lines and whether it is necessary?

https://github.com/lucidrains/feedback-transformer-pytorch/blob/d7d8939910d1491f01a3d93ce81d4663925fb389/feedback_transformer_pytorch/feedback_transformer_pytorch.py#L146-L151

It looks to me that line 146 transforms the output of the layer below (`x`) to keys and values, and the following lines combine these keys and values with the memory. I thought that `x` should only be used for forming the query here, and only the existing memory is used for keys and values.

**Comment by lucidrains** [comment]
I kind of strayed off course from the paper and allow sequential processing of more than a token at a time (using seq_len), in which case this would be necessary (as well as the subsequent causal masking)

But you are right that if we were to strictly process one token at a time, this extra key value wouldn't need to be computed

**Comment by lucidrains** [comment]
@tarvaina if it were the case that each token only cross attends to the memory, would the attention block be skipped altogether on the first step, when there is no memory yet?

**Comment by tarvaina** [comment]
Thanks for your response. Yeah, I was also wondering about `seq_len` and figured it would be something like that.

> @tarvaina if it were the case that each token only cross attends to the memory, would the attention block be skipped altogether on the first step, when there is no memory yet?

That's my understanding. I also looked at the labml-nn implementation and they seem to skip attention for the first step. See here: https://github.com/lab-ml/nn/blob/a491429ba1296677de2f207e697e36be3c6745ac/labml_nn/transformers/feedback/__init__.py#L233-L234

**Comment by lucidrains** [comment]
@tarvaina ok! i'll make it so if the length is 1, then it does what you describe

**Comment by lucidrains** [comment]
@tarvaina ok done! let me know if that works for you https://github.com/lucidrains/feedback-transformer-pytorch/commit/60f98187905b58c55f0a3061201d10a8f7d49122

**Comment by tarvaina** [comment]
Thanks!
