### ISSUE TITLE
In place operation with gradient

### ISSUE THREAD

**Issue by hadaev8** [lucidrains/feedback-transformer-pytorch#5]
https://github.com/lucidrains/feedback-transformer-pytorch/blob/main/feedback_transformer_pytorch/feedback_transformer_pytorch.py#L173
I think this is an error.

**Comment by lucidrains** [comment]
Ohh, could you expand on that?

**Comment by hadaev8** [comment]
As far as I understand autograd, in-place operation should not be used over values with the gradient (trainable params).

The tutorial just says don't use it.

https://pytorch.org/docs/stable/notes/autograd.html

**Comment by lucidrains** [comment]
Ah got it! Yup agreed it should be avoided, let me know if the recent commit will do!

**Comment by hadaev8** [comment]
Yes.
