### ISSUE TITLE
Bug in weighted sum

### ISSUE THREAD

**Issue by Victor0118** [lucidrains/feedback-transformer-pytorch#8]
Bug in https://github.com/lucidrains/feedback-transformer-pytorch/blob/main/feedback_transformer_pytorch/feedback_transformer_pytorch.py#L264

Should be `layer_weight = rearrange(layer_weight, 'd -> d () () ()')`

**Comment by lucidrains** [comment]
@Victor0118 thanks Victor! fixed in the latest release!
